<Project Sdk="Microsoft.NET.Sdk.Razor">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>

  <ItemGroup>
    <SupportedPlatform Include="browser" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.AspNetCore.Components.Web" />
    <PackageReference Include="Telerik.UI.for.Blazor" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\..\Core\Standup.Application\Standup.Application.csproj" />
  </ItemGroup>

</Project>
